const role = {
  name: 'role',
  form: [
    { name: '_isAdmin', removable: false, reorderable: true },
    { name: '_viewContact', removable: false, reorderable: true },
    { name: '_viewAccount', removable: false, reorderable: true },
    { name: '_viewDeal', removable: false, reorderable: true },
    { name: '_createContact', removable: false, reorderable: true },
    { name: '_createAccount', removable: false, reorderable: true },
    { name: '_createDeal', removable: false, reorderable: true },
    { name: '_createEmail', removable: false, reorderable: true },
    { name: '_createEvent', removable: false, reorderable: true },
    { name: '_createTask', removable: false, reorderable: true },
    { name: '_editContact', removable: false, reorderable: true },
    { name: '_editAccount', removable: false, reorderable: true },
    { name: '_editDeal', removable: false, reorderable: true },
    { name: '_editTask', removable: false, reorderable: true },
    { name: '_editEvent', removable: false, reorderable: true },
    { name: '_deleteContact', removable: false, reorderable: true },
    { name: '_deleteAccount', removable: false, reorderable: true },
    { name: '_deleteDeal', removable: false, reorderable: true },
    { name: '_deleteEvent', removable: false, reorderable: true },
    { name: '_deleteTask', removable: false, reorderable: true },
  ],
  table: [],
  infoBox: [],
};
export default role;
