const fields = [
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'First Name',
    inputType: 'Text',
    name: '_firstName',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Last Name',
    inputType: 'Text',
    name: '_lastName',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Email',
    inputType: 'Email',
    name: '_email',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Organization Name',
    inputType: 'Text',
    name: '_organizationName',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Password',
    inputType: 'Password',
    name: '_password',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Is Admin',
    inputType: 'Checkbox',
    name: '_isAdmin',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'View Contact',
    inputType: 'Checkbox',
    name: '_viewContact',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'View Account',
    inputType: 'Checkbox',
    name: '_viewAccount',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'View Deal',
    inputType: 'Checkbox',
    name: '_viewDeal',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Create Contact',
    inputType: 'Checkbox',
    name: '_createContact',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Create Account',
    inputType: 'Checkbox',
    name: '_createAccount',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Create Deal',
    inputType: 'Checkbox',
    name: '_createDeal',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Create Email',
    inputType: 'Checkbox',
    name: '_createEmail',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Create Event',
    inputType: 'Checkbox',
    name: '_createEvent',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Create Task',
    inputType: 'Checkbox',
    name: '_createTask',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Edit Contact',
    inputType: 'Checkbox',
    name: '_editContact',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Edit Account',
    inputType: 'Checkbox',
    name: '_editAccount',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Edit Deal',
    inputType: 'Checkbox',
    name: '_editDeal',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Edit Task',
    inputType: 'Checkbox',
    name: '_editTask',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Edit Event',
    inputType: 'Checkbox',
    name: '_editEvent',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Delete Contact',
    inputType: 'Checkbox',
    name: '_deleteContact',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Delete Account',
    inputType: 'Checkbox',
    name: '_deleteAccount',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Delete Deal',
    inputType: 'Checkbox',
    name: '_deleteDeal',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Delete Event',
    inputType: 'Checkbox',
    name: '_deleteEvent',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Delete Task',
    inputType: 'Checkbox',
    name: '_deleteTask',
    helpText: '',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      editListSource: false,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Stages',
    inputType: 'Picklist',
    name: '_stages',
    helpText: '',
    listSource: 'stages',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      editListSource: false,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Items',
    inputType: 'Picklist',
    name: '_items',
    helpText: '',
    listSource: 'items',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      editSearchSource: false,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Rules',
    inputType: 'Search',
    name: '_rules',
    helpText: '',
    searchSource: 'Validation',
    validation: [],
  },
  {
    permissions: {
      public: false,
      editInputType: false,
      editInputLabel: true,
      editHelpText: true,
      editListSource: true,
      isDeletable: true,
      editValidation: true,
    },
    inputLabel: 'Role',
    inputType: 'Picklist',
    name: '_role',
    helpText: '',
    listSource: 'role',
    validation: [],
  },
];
export default fields;
