/**
 * Data used to build default forms, pipelines, and roles for a new organization.
 */

export const contactForm = [
  {
    input_type: 'text',
    input_label: 'First Name',
    help_text: '',
    form: { order: 1, visible: true },
    list: { order: 1, visible: true },
    field_name: 'first_name',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'text',
    input_label: 'Last Name',
    help_text: '',
    form: { order: 2, visible: true },
    list: { order: 2, visible: true },
    field_name: 'last_name',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'email',
    input_label: 'Email',
    help_text: '',
    form: { order: 3, visible: true },
    list: { order: 3, visible: true },
    field_name: 'email',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'phone',
    input_label: 'Phone',
    help_text: '',
    form: { order: 4, visible: true },
    list: { order: 4, visible: true },
    field_name: 'phone',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'text',
    input_label: 'Company',
    help_text: '',
    form: { order: 5, visible: true },
    list: { order: 5, visible: true },
    field_name: 'company',
    deletable: false,
    data_source: '[],',
  },
  {
    input_type: 'text',
    input_label: 'Job Title',
    help_text: '',
    form: { order: 6, visible: true },
    list: { order: 6, visible: true },
    field_name: 'job_title',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'picklist',
    input_label: 'Owner',
    help_text: '',
    form: { order: 7, visible: true },
    list: { order: 7, visible: true },
    field_name: 'owner',
    deletable: false,
    data_source: 'profiles',
  },
];

export const accountForm = [
  {
    input_type: 'text',
    input_label: 'Name',
    help_text: '',
    form: { order: 1, visible: true },
    list: { order: 1, visible: true },
    field_name: 'name',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'phone',
    input_label: 'Phone',
    help_text: '',
    form: { order: 2, visible: true },
    list: { order: 2, visible: true },
    field_name: 'phone',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'text',
    input_label: 'Address',
    help_text: '',
    form: { order: 3, visible: true },
    list: { order: 3, visible: true },
    field_name: 'address',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'picklist',
    input_label: 'Owner',
    help_text: '',
    form: { order: 4, visible: true },
    list: { order: 4, visible: true },
    field_name: 'owner',
    deletable: false,
    data_source: 'profiles',
  },
  {
    input_type: 'search',
    input_label: 'Associated Contacts',
    help_text: '',
    form: { order: 5, visible: true },
    list: { order: 5, visible: true },
    field_name: 'associated_contacts',
    deletable: false,
    data_source: 'contact',
  },
  {
    input_type: 'url',
    input_label: 'Website',
    help_text: 'Company website',
    form: { order: 6, visible: true },
    list: { order: 6, visible: true },
    field_name: 'website',
    deletable: false,
    data_source: '',
  },
];

export const dealForm = [
  {
    input_type: 'text',
    input_label: 'Name',
    help_text: '',
    form: { order: 1, visible: true },
    list: { order: 1, visible: true },
    field_name: 'name',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'number',
    input_label: 'Value',
    help_text: '',
    form: { order: 2, visible: true },
    list: { order: 2, visible: true },
    field_name: 'value',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'picklist',
    input_label: 'Owner',
    help_text: '',
    form: { order: 3, visible: true },
    list: { order: 3, visible: true },
    field_name: 'owner',
    deletable: false,
    data_source: 'profiles',
  },
  {
    input_type: 'date',
    input_label: 'Close Date',
    help_text: '',
    form: { order: 4, visible: true },
    list: { order: 4, visible: true },
    field_name: 'close_date',
    deletable: false,
    data_source: '',
  },
  {
    input_type: 'picklist',
    input_label: 'Pipeline',
    help_text: '',
    form: { order: 5, visible: true },
    list: { order: 5, visible: true },
    field_name: 'pipeline',
    deletable: false,
    data_source: 'pipelines',
  },
  {
    input_type: 'picklist',
    input_label: 'Current Stage',
    help_text: '',
    form: { order: 6, visible: true },
    list: { order: 6, visible: true },
    field_name: 'current_stage',
    deletable: false,
    data_source: 'pipelines',
  },
  {
    input_type: 'search',
    input_label: 'Associated Contacts',
    help_text: '',
    form: { order: 7, visible: true },
    list: { order: 7, visible: true },
    field_name: 'associated_contacts',
    deletable: false,
    data_source: 'contact',
  },
  {
    input_type: 'picklist',
    input_label: 'Currency',
    help_text: '',
    form: { order: 8, visible: true },
    list: { order: 8, visible: true },
    field_name: 'currency',
    deletable: false,
    data_source: 'currency',
  },
  {
    input_type: 'picklist',
    input_label: 'Deal Status',
    help_text: '',
    form: { order: 9, visible: true },
    list: { order: 9, visible: true },
    field_name: 'deal_status',
    deletable: false,
    data_source: 'deal_status',
  },
];

export const pipeline = {
  name: 'Deal',
  stages: [{ stage_name: 'Start', order: 1 }],
};

//Roles
export const adminRole = {
  view: {
    contact: true,
    account: true,
    deal: true,
  },
  create: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
    email: true,
  },
  edit: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  delete_: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  is_admin: true,
};

export const managerRole = {
  view: {
    contact: true,
    account: true,
    deal: true,
  },
  create: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
    email: true,
  },
  edit: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  delete_: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  is_admin: false,
};
