/**
 * Data used to build default forms, pipelines, and roles for a new organization.
 */

export const contactForm = [
  {
    inputType: 'text',
    inputLabel: 'First Name',
    helpText: '',
    form: { order: 1, visible: true },
    list: { order: 1, visible: true },
    fieldName: 'first_name',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'text',
    inputLabel: 'Last Name',
    helpText: '',
    form: { order: 2, visible: true },
    list: { order: 2, visible: true },
    fieldName: 'last_name',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'email',
    inputLabel: 'Email',
    helpText: '',
    form: { order: 3, visible: true },
    list: { order: 3, visible: true },
    fieldName: 'email',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'phone',
    inputLabel: 'Phone',
    helpText: '',
    form: { order: 4, visible: true },
    list: { order: 4, visible: true },
    fieldName: 'phone',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'text',
    inputLabel: 'Company',
    helpText: '',
    form: { order: 5, visible: true },
    list: { order: 5, visible: true },
    fieldName: 'company',
    deletable: false,
    dataSource: '[],',
  },
  {
    inputType: 'text',
    inputLabel: 'Job Title',
    helpText: '',
    form: { order: 6, visible: true },
    list: { order: 6, visible: true },
    fieldName: 'job_title',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Owner',
    helpText: '',
    form: { order: 7, visible: true },
    list: { order: 7, visible: true },
    fieldName: 'owner',
    deletable: false,
    dataSource: 'profiles',
  },
];

export const accountForm = [
  {
    inputType: 'text',
    inputLabel: 'Company',
    helpText: '',
    form: { order: 1, visible: true },
    list: { order: 1, visible: true },
    fieldName: 'company',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'phone',
    inputLabel: 'Phone',
    helpText: '',
    form: { order: 2, visible: true },
    list: { order: 2, visible: true },
    fieldName: 'phone',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'text',
    inputLabel: 'Address',
    helpText: '',
    form: { order: 3, visible: true },
    list: { order: 3, visible: true },
    fieldName: 'address',
    deletable: false,
    listOptions: '',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Owner',
    helpText: '',
    form: { order: 4, visible: true },
    list: { order: 4, visible: true },
    fieldName: 'owner',
    deletable: false,
    dataSource: 'profiles',
  },
  {
    inputType: 'search',
    inputLabel: 'Associated Contacts',
    helpText: '',
    form: { order: 5, visible: true },
    list: { order: 5, visible: true },
    fieldName: 'associated_contacts',
    deletable: false,
    dataSource: 'contact',
  },
  {
    inputType: 'url',
    inputLabel: 'Website',
    helpText: 'Company website',
    form: { order: 6, visible: true },
    list: { order: 6, visible: true },
    fieldName: 'website',
    deletable: false,
    listSource: '',
  },
];

export const dealForm = [
  {
    inputType: 'text',
    inputLabel: 'Title',
    helpText: '',
    form: { order: 1, visible: true },
    list: { order: 1, visible: true },
    fieldName: 'title',
    deletable: false,
    listSource: '',
  },
  {
    inputType: 'number',
    inputLabel: 'Value',
    helpText: '',
    form: { order: 2, visible: true },
    list: { order: 2, visible: true },
    fieldName: 'value',
    deletable: false,
    listSource: '',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Owner',
    helpText: '',
    form: { order: 3, visible: true },
    list: { order: 3, visible: true },
    fieldName: 'owner',
    deletable: false,
    dataSource: 'profiles',
  },
  {
    inputType: 'date',
    inputLabel: 'Close Date',
    helpText: '',
    form: { order: 4, visible: true },
    list: { order: 4, visible: true },
    fieldName: 'close_date',
    deletable: false,
    dataSource: '',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Pipeline',
    helpText: '',
    form: { order: 5, visible: true },
    list: { order: 5, visible: true },
    fieldName: 'pipeline',
    deletable: false,
    dataSource: 'pipelines',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Current Stage',
    helpText: '',
    form: { order: 6, visible: true },
    list: { order: 6, visible: true },
    fieldName: 'current_stage',
    deletable: false,
    dataSource: 'pipelines',
  },
  {
    inputType: 'search',
    inputLabel: 'Associated Contacts',
    helpText: '',
    form: { order: 7, visible: true },
    list: { order: 7, visible: true },
    fieldName: 'associated_contacts',
    deletable: false,
    dataSource: 'contact',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Currency',
    helpText: '',
    form: { order: 8, visible: true },
    list: { order: 8, visible: true },
    fieldName: 'currency',
    deletable: false,
    dataSource: 'currency',
  },
  {
    inputType: 'picklist',
    inputLabel: 'Deal Status',
    helpText: '',
    form: { order: 9, visible: true },
    list: { order: 9, visible: true },
    fieldName: 'deal_status',
    deletable: false,
    dataSource: 'deal_status',
  },
];

export const pipeline = {
  name: 'Deal',
  stages: [{ stageName: 'Start', order: 1 }],
};

//Roles
export const adminRole = {
  view: {
    contact: true,
    account: true,
    deal: true,
  },
  create: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
    email: true,
  },
  edit: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  delete_: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  isAdmin: true,
};

export const managerRole = {
  view: {
    contact: true,
    account: true,
    deal: true,
  },
  create: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
    email: true,
  },
  edit: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  delete_: {
    contact: true,
    account: true,
    deal: true,
    event: true,
    task: true,
  },
  isAdmin: false,
};
